### ISSUE TITLE
Misplace of the word "ต่ำ"

### ISSUE THREAD

**Issue by piyasil** [cadsondemak/Anuphan#3]
คำว่า ต่ำ สระอยู่ผิดที่

Tested on:
Variable font downloaded from Google Fonts

<img width="1439" alt="Screenshot 2566-07-24 at 23 49 43" src="https://github.com/cadsondemak/Anuphan/assets/13187366/8ef510b7-23bc-4020-9918-29068154406a">

**Comment by kanorider** [comment]
ขอบคุณที่แจ้งมาครับ แนะนำให้ใช้เวอร์ชันที่อยู่ใน github แทนนะครับ

**Comment by piyasil** [comment]
ได้แล้วครับ ขอบคุณครับ
